=== philbarker/lr_schema/lr1_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "lr_schema.json",
  "name": "JSON Schema for schema.org Learning Resource",
  "description": "Attempt at a JSON Schema to create valid schema.org/LRMI JSON-LD descriptions of learning resources",
  "type": "object",
  "required": [
    "@context",
    "@id",
    "@type"
  ],
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "object",
      "name": "JSON Schema for @context of schema.org Learning Resource",
      "description": "schema.org is @base namespace but others are allowed",
      "$ref": "./context.json"
    },
    "@id": {
      "name": "URI @ids",
      "description": "required: @id is a http or https URI",
      "$ref": "http_uri_schema.json"
    },
    "@type": {
      "$ref": "type_lr_schema.json"
    },
    "name": {
      "type": "string"
    },
    "url": {
      "$ref": "http_uri_schema.json",
      "description": "required: url is a http or https URI"
    },
    "teaches": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "@id": {
          "name": "URI @ids",
          "description": "required: @id is a http or https URI; no bnodes refs here",
          "$ref": "http_uri_schema.json"
        },
        "@type": {
          "type": "string",
          "format": "regex",
          "pattern": "DefinedTerm"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "termCode": {
          "type": "string"
        },
        "inDefinedTermSet": {
          "type": "string"
        }
      }
    }
  }
}

=== philbarker/lr_schema/lr_valid.json
{
  "@context": {
    "@vocab": "http://schema.org/",
    "oer": "http://oerschema.org"
  },
  "@id": "https://example.org/test#webpage",
  "@type": [
    "LearningResource",
    "WebPage"
  ],
  "name": "anything",
  "url": "http://example.org/test",
  "teaches": {
    "@id": "http://example.org/concept",
    "@type": "DefinedTerm",
    "name": "Add and subtract within 20",
    "termCode": "CCSS.MATH.CONTENT.1.OA.C.5",
    "inDefinedTermSet": "Common Core State Standards. Math."
  }
}
